# Generated by Django 5.2.4 on 2025-07-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
